const CardData = [
	{
		profilesrc: '/img/destiny-profile.png',
		createrName: 'Ehror',
		imagesrc: '/img/gamereview.jpg',
		gameTitle: 'Destiny 2',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/beamng-profile.png',
		createrName: 'Jayy',
		imagesrc: '/img/BeamNG.png',
		gameTitle: 'Teardown',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/lorestar-profile.png',
		createrName: 'Rodey Bros',
		imagesrc: '/img/lorestar.png',
		gameTitle: 'Cyberpunk 2077',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/bigb-profile.png',
		createrName: 'Massive G',
		imagesrc: '/img/Bigb.png',
		gameTitle: 'Far Cry 6',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/destiny-profile.png',
		createrName: 'Lore star',
		imagesrc: '/img/gamereview.jpg',
		gameTitle: 'Star War: Night of the old people',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/beamng-profile.png',
		createrName: 'Bottlecap',
		imagesrc: '/img/BeamNG.png',
		gameTitle: 'Microsoft Flight Simulator',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/lorestar-profile.png',
		createrName: 'Big B',
		imagesrc: '/img/lorestar.png',
		gameTitle: 'Mine Craft',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/bigb-profile.png',
		createrName: 'Ehhhora',
		imagesrc: '/img/Bigb.png',
		gameTitle: 'Destiny',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/destiny-profile.png',
		createrName: 'Lore star',
		imagesrc: '/img/gamereview.jpg',
		gameTitle: 'Star War: Night of the old people',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/beamng-profile.png',
		createrName: 'Bottlecap',
		imagesrc: '/img/BeamNG.png',
		gameTitle: 'Microsoft Flight Simulator',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/lorestar-profile.png',
		createrName: 'Big B',
		imagesrc: '/img/lorestar.png',
		gameTitle: 'Mine Craft',
		Rating: '9.2',
	},
	{
		profilesrc: '/img/bigb-profile.png',
		createrName: 'Ehhhora',
		imagesrc: '/img/Bigb.png',
		gameTitle: 'Destiny',
		Rating: '9.2',
	},
];
export default CardData;
